Fix a compile error exposed by gregoryd when building NaCl on Windows:
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2332: 'struct' : missing tag name
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2332: 'struct' : missing tag name
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2144: syntax error : '<unnamed-tag>' should be preceded by ')'
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2144: syntax error : '<unnamed-tag>' should be preceded by ';'
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2059: syntax error : ')'
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2332: 'struct' : missing tag name
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2144: syntax error : '<unnamed-tag>' should be preceded by ')'
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C3861: 'interface_': identifier not found
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2150: 'pp::Core::<alignment member>' : bit field must have type 'int', 'signed int', or 'unsigned int'
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2059: syntax error : '{'
C:\b\slave\nacl-win32_dbg\build\ppapi/cpp/core.h(50) : error C2334: unexpected token(s) preceding '{'; skipping apparent function body


Review URL: http://codereview.chromium.org/3110017